// Code generated by goctl. DO NOT EDIT.
// Source: comment.proto

package server

import (
	"context"

	"snkrs/apps/rpc_service/comment/comment"
	"snkrs/apps/rpc_service/comment/internal/logic"
	"snkrs/apps/rpc_service/comment/internal/svc"
)

type CommentServiceServer struct {
	svcCtx *svc.ServiceContext
	comment.UnimplementedCommentServiceServer
}

func NewCommentServiceServer(svcCtx *svc.ServiceContext) *CommentServiceServer {
	return &CommentServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *CommentServiceServer) Comments(ctx context.Context, in *comment.CommentsRequest) (*comment.CommentsResponse, error) {
	l := logic.NewCommentsLogic(ctx, s.svcCtx)
	return l.Comments(in)
}
