// Code generated by goctl. DO NOT EDIT.
// Source: reserve.proto

package server

import (
	"context"

	"snkrs/apps/rpc_service/reserve/rpc/internal/logic"
	"snkrs/apps/rpc_service/reserve/rpc/internal/svc"
	"snkrs/apps/rpc_service/reserve/rpc/reserve"
)

type ReserveServiceServer struct {
	svcCtx *svc.ServiceContext
	reserve.UnimplementedReserveServiceServer
}

func NewReserveServiceServer(svcCtx *svc.ServiceContext) *ReserveServiceServer {
	return &ReserveServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ReserveServiceServer) ReserveOrder(ctx context.Context, in *reserve.ReserveOrderRequest) (*reserve.ReserveOrderResponse, error) {
	l := logic.NewReserveOrderLogic(ctx, s.svcCtx)
	return l.ReserveOrder(in)
}
