version: "3"
services:
  mysql:
    image: mysql:latest
    container_name: snkrs-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_PASSWORD: 123456
    privileged: true
    restart: always
    networks:
      - snkrs-network

  etcd:
    image: bitnami/etcd:latest
    container_name: snkrs-etcd
    ports:
      - "2379:2379"
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
    restart: always
    networks:
      - snkrs-network

  redis:
    image: redis:latest
    container_name: snkrs-redis
    privileged: true
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    restart: always
    networks:
      - snkrs-network

  zookeeper:
    image: zookeeper:latest
    container_name: snkrs-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
    restart: always
    networks:
      - snkrs-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: snkrs-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: always
    depends_on:
      - zookeeper
    networks:
      - snkrs-network

networks:
  snkrs-network:
