// Code generated by goctl. DO NOT EDIT.
// Source: product.proto

package productservice

import (
	"context"

	"snkrs/apps/rpc_service/product/product"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CheckAndUpdateStockRequest  = product.CheckAndUpdateStockRequest
	CheckAndUpdateStockResponse = product.CheckAndUpdateStockResponse
	OperationProductsRequest    = product.OperationProductsRequest
	OperationProductsResponse   = product.OperationProductsResponse
	ProductItem                 = product.ProductItem
	ProductItemRequest          = product.ProductItemRequest
	ProductListRequest          = product.ProductListRequest
	ProductListResponse         = product.ProductListResponse
	ProductRequest              = product.ProductRequest
	ProductResponse             = product.ProductResponse
	UpdateProductStockRequest   = product.UpdateProductStockRequest
	UpdateProductStockResponse  = product.UpdateProductStockResponse

	ProductService interface {
		Product(ctx context.Context, in *ProductItemRequest, opts ...grpc.CallOption) (*ProductItem, error)
		Products(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (*ProductResponse, error)
		ProductList(ctx context.Context, in *ProductListRequest, opts ...grpc.CallOption) (*ProductListResponse, error)
		OperationProducts(ctx context.Context, in *OperationProductsRequest, opts ...grpc.CallOption) (*OperationProductsResponse, error)
		UpdateProductStock(ctx context.Context, in *UpdateProductStockRequest, opts ...grpc.CallOption) (*UpdateProductStockResponse, error)
		CheckAndUpdateStock(ctx context.Context, in *CheckAndUpdateStockRequest, opts ...grpc.CallOption) (*CheckAndUpdateStockResponse, error)
	}

	defaultProductService struct {
		cli zrpc.Client
	}
)

func NewProductService(cli zrpc.Client) ProductService {
	return &defaultProductService{
		cli: cli,
	}
}

func (m *defaultProductService) Product(ctx context.Context, in *ProductItemRequest, opts ...grpc.CallOption) (*ProductItem, error) {
	client := product.NewProductServiceClient(m.cli.Conn())
	return client.Product(ctx, in, opts...)
}

func (m *defaultProductService) Products(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (*ProductResponse, error) {
	client := product.NewProductServiceClient(m.cli.Conn())
	return client.Products(ctx, in, opts...)
}

func (m *defaultProductService) ProductList(ctx context.Context, in *ProductListRequest, opts ...grpc.CallOption) (*ProductListResponse, error) {
	client := product.NewProductServiceClient(m.cli.Conn())
	return client.ProductList(ctx, in, opts...)
}

func (m *defaultProductService) OperationProducts(ctx context.Context, in *OperationProductsRequest, opts ...grpc.CallOption) (*OperationProductsResponse, error) {
	client := product.NewProductServiceClient(m.cli.Conn())
	return client.OperationProducts(ctx, in, opts...)
}

func (m *defaultProductService) UpdateProductStock(ctx context.Context, in *UpdateProductStockRequest, opts ...grpc.CallOption) (*UpdateProductStockResponse, error) {
	client := product.NewProductServiceClient(m.cli.Conn())
	return client.UpdateProductStock(ctx, in, opts...)
}

func (m *defaultProductService) CheckAndUpdateStock(ctx context.Context, in *CheckAndUpdateStockRequest, opts ...grpc.CallOption) (*CheckAndUpdateStockResponse, error) {
	client := product.NewProductServiceClient(m.cli.Conn())
	return client.CheckAndUpdateStock(ctx, in, opts...)
}
