// Code generated by goctl. DO NOT EDIT.
// Source: comment.proto

package comment

import (
	"context"


	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (


	Comment interface {
		Comments(ctx context.Context, in *CommentsRequest, opts ...grpc.CallOption) (*CommentsResponse, error)
	}

	defaultComment struct {
		cli zrpc.Client
	}
)

func NewComment(cli zrpc.Client) Comment {
	return &defaultComment{
		cli: cli,
	}
}

func (m *defaultComment) Comments(ctx context.Context, in *CommentsRequest, opts ...grpc.CallOption) (*CommentsResponse, error) {
	client := NewCommentClient(m.cli.Conn())
	return client.Comments(ctx, in, opts...)
}
