// Code generated by goctl. DO NOT EDIT.
package types

type Empty struct {
}

type Banner struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	URL  string `json:"url"`
}

type HomeBannerResponse struct {
	Banners []*Banner `json:"banners"`
}

type LimitedSaleResponse struct {
	StartTime int64      `json:"start_time"` // limited sale start time
	Products  []*Product `json:"products"`
}

type Product struct {
	ID          int64    `json:"id"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Images      []string `json:"images"`
	Price       float64  `json:"price"`
	Stock       int64    `json:"stock"`
	Category    string   `json:"category"`
	Status      int64    `json:"status"` // 1 in stock, 0 out of stock
	CreateTime  int64    `json:"create_time"`
	UpdateTime  int64    `json:"update_time"`
}

type CategoryListRequest struct {
	Cursor   int64  `form:"cursor"`
	Ps       int64  `form:"ps,default=20"` // size of page
	Category string `form:"category"`
	Sort     string `form:"sort"`
}

type CategoryListResponse struct {
	Products []*Product `json:"products"`
	IsEnd    bool       `json:"is_end"`
	LastVal  int64      `json:"last_val"`
}

type ProductCommentRequest struct {
	ProductID int64 `form:"product_id"`
	Cursor    int64 `form:"cursor"`
	Ps        int64 `form:"ps,default=20"`
}

type ProductCommentResponse struct {
	Comments    []*Comment `json:"comments"`
	IsEnd       bool       `json:"is_end"`       // is last page
	CommentTime int64      `json:"comment_time"` // the last command time in comment list
}

type Comment struct {
	ID         int64  `json:"id"`          // comment id
	ProductID  int64  `json:"product_id"`  // product id
	Content    string `json:"content"`     // comment content
	User       *User  `json:"user"`        // user info
	CreateTime int64  `json:"create_time"` // create time
	UpdateTime int64  `json:"update_time"` // update time
}

type User struct {
	ID   int64  `json:"id"`   // user id
	Name string `json:"name"` // user name
}

type OrderListRequest struct {
	UID    int64 `form:"uid"`
	Status int32 `form:"status,optional"`
	Cursor int64 `form:"cursor,optional"`
	Ps     int64 `form:"ps,default=20"`
}

type OrderListResponse struct {
	Orders    []*Order `json:"orders"`
	IsEnd     bool     `json:"is_end"` // is last page
	OrderTime int64    `json:"order_time"`
}

type Order struct {
	OrderID            string  `json:"order_id"`
	Status             int32   `json:"status"`
	Quantity           int64   `json:"quantity"`
	Payment            float64 `json:"payment"`
	TotalPrice         float64 `json:"total_price"`
	CreateTime         int64   `json:"create_time"`
	ProductID          int64   `json:"product_id"`
	ProductName        string  `json:"product_name"`
	ProductImage       string  `json:"product_image"`
	ProductDescription string  `json:"product_description"`
}

type ProductDetailRequest struct {
	ProductID int64 `form:"product_id"`
}

type ProductDetailResponse struct {
	Product  *Product   `json:"product"`
	Comments []*Comment `json:"comments"`
}

type ReserveProductRequest struct {
	UserID    int64 `form:"user_id"`
	ProductID int64 `form:"product_id"`
}

type ReserveProductResponse struct {
	Message string `json:"message"`
}
